on:
  issues:
    types: [opened]

jobs:
  comment_on_new_issue:
    runs-on: ubuntu-latest
    name: Job for commenting on new issue
    steps:
      - name: Comment
        uses: jd-0001/gh-action-comment-on-new-issue@v2.0.3
        with:
          message: 'Hello @${{ github.actor }} , thank you for submitting an issue!'
